

cx.secretStr = cr[0];
cx.buttonTextInfo = cr[1];
var cv = [];
cv.train_no = cr[2];
cv.station_train_code = cr[3];
cv.start_station_telecode = cr[4];
cv.end_station_telecode = cr[5];
cv.from_station_telecode = cr[6];
cv.to_station_telecode = cr[7];
cv.start_time = cr[8];
cv.arrive_time = cr[9];
cv.lishi = cr[10];
cv.canWebBuy = cr[11];
cv.yp_info = cr[12];
cv.start_train_date = cr[13];
cv.train_seat_feature = cr[14];
cv.location_code = cr[15];
cv.from_station_no = cr[16];
cv.to_station_no = cr[17];
cv.is_support_card = cr[18];
cv.controlled_train_flag = cr[19];
cv.gg_num = cr[20] ? cr[20] : "--";
cv.gr_num = cr[21] ? cr[21] : "--";    高等软卧
cv.qt_num = cr[22] ? cr[22] : "--";    其他
cv.rw_num = cr[23] ? cr[23] : "--";    软卧
cv.rz_num = cr[24] ? cr[24] : "--";    软座
cv.tz_num = cr[25] ? cr[25] : "--";    特等座
cv.wz_num = cr[26] ? cr[26] : "--";    无座
cv.yb_num = cr[27] ? cr[27] : "--";
cv.yw_num = cr[28] ? cr[28] : "--";    硬卧
cv.yz_num = cr[29] ? cr[29] : "--";    硬座
cv.ze_num = cr[30] ? cr[30] : "--";    二等座
cv.zy_num = cr[31] ? cr[31] : "--";    一等座
cv.swz_num = cr[32] ? cr[32] : "--";   商务座
cv.srrb_num = cr[33] ? cr[33] : "--";  动卧
cv.yp_ex = cr[34];
cv.seat_types = cr[35];
cv.exchange_train_flag = cr[36];
cv.from_station_name = cw[cr[6]];
cv.to_station_name = cw[cr[7]];
cx.queryLeftNewDTO = cv;
